//-----------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs" company="Sitecore Corporation">
//     Copyright (c) Sitecore Corporation 1999-2016
// </copyright>
//-----------------------------------------------------------------------

// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Code Analysis results, point to "Suppress Message", and click 
// "In Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.BasketViewModel.#BasketErrors")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "Sitecore.Reference.Storefront.Controllers.AccountController+ManageMessageId")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "Filename", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.IImageEntity.#ImageFilename")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "Filename", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.LineItemViewModel.#ImageFilename")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sitecore", Scope = "namespace", Target = "Sitecore.Reference.Storefront.SitecorePipelines")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.CommerceImage.#Uri")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.SitecoreItemModels.SitecoreItemBase.#Item")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.SitecoreItemModels.PromoList.#Promotions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.Promotions.PromoRotatorViewModel.#Promotions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "Sitecore.Reference.Storefront.Controllers.CatalogController.#CommerceNamedSearchTemplate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.RegisterModel.#Errors")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "shippings", Scope = "member", Target = "Sitecore.Reference.Storefront.Controllers.CheckoutController.#SetShippingMethods(System.String,System.Collections.Generic.IEnumerable`1<Sitecore.Commerce.Connect.DynamicsRetail.Models.CommerceShippingInfo>,System.Collections.Generic.IEnumerable`1<Sitecore.Commerce.Connect.CommerceServer.Orders.Models.CommerceParty>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "shippings", Scope = "member", Target = "Sitecore.Reference.Storefront.Services.ICartService.#AddShippingInfoToCart(System.String,System.Collections.Generic.IEnumerable`1<Sitecore.Commerce.Connect.DynamicsRetail.Models.CommerceShippingInfo>,System.Collections.Generic.IEnumerable`1<Sitecore.Commerce.Connect.CommerceServer.Orders.Models.CommerceParty>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "shippings", Scope = "member", Target = "Sitecore.Reference.Storefront.Controllers.CheckoutController.#SetShippingMethods(System.String,System.Collections.Generic.IEnumerable`1<Sitecore.Commerce.Connect.DynamicsRetail.Models.CommerceShippingInfo>,System.Collections.Generic.IEnumerable`1<Sitecore.Commerce.Connect.DynamicsRetail.Models.CommerceParty>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "Sitecore.Reference.Storefront.Controllers.CheckoutController.#AddSupportingDataToViewBag(Sitecore.Commerce.Connect.CommerceServer.Orders.Models.CommerceCart,System.Boolean,Sitecore.Commerce.Connect.DynamicsRetail.Models.ShippingOptionType)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "member", Target = "Sitecore.Reference.Storefront.Controllers.CheckoutController.#AddSupportingDataToViewBag(Sitecore.Commerce.Connect.CommerceServer.Orders.Models.CommerceCart,System.Boolean,Sitecore.Commerce.Connect.DynamicsRetail.Models.ShippingOptionType)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "shippings", Scope = "member", Target = "Sitecore.Reference.Storefront.Services.ICartService.#AddShippingInfoToCart(Sitecore.Commerce.Connect.CommerceServer.Orders.Models.CommerceCart,Sitecore.Commerce.Connect.DynamicsRetail.Models.ShippingOptionType,System.Collections.Generic.IEnumerable`1<Sitecore.Commerce.Connect.DynamicsRetail.Models.CommerceShippingInfo>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "Sitecore.Reference.Storefront.Controllers.CheckoutController.#AddSupportingDataToViewBag(Sitecore.Commerce.Connect.CommerceServer.Orders.Models.CommerceCart,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "shippings", Scope = "member", Target = "Sitecore.Reference.Storefront.Services.ICartService.#AddShippingInfoToCart(Sitecore.Commerce.Connect.CommerceServer.Orders.Models.CommerceCart,Sitecore.Commerce.Connect.DynamicsRetail.Models.ShippingPreferenceType,System.Collections.Generic.IEnumerable`1<Sitecore.Commerce.Connect.DynamicsRetail.Models.CommerceShippingInfo>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "Sitecore.Reference.Storefront.Controllers.CheckoutController")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "member", Target = "Sitecore.Reference.Storefront.Controllers.CheckoutController.#SetShippingMethods(System.String,System.Collections.Generic.IEnumerable`1<Sitecore.Commerce.Connect.DynamicsRetail.Models.CommerceShippingInfo>,System.Collections.Generic.IEnumerable`1<Sitecore.Commerce.Connect.DynamicsRetail.Models.CommerceParty>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "member", Target = "Sitecore.Reference.Storefront.Controllers.CheckoutController.#SubmitOrder(System.String,Sitecore.Commerce.Connect.CommerceServer.Orders.Models.CommerceCreditCardPaymentInfo,Sitecore.Commerce.Connect.DynamicsRetail.Models.CommerceParty,Sitecore.Commerce.Connect.DynamicsRetail.Models.CommerceGiftCardPaymentInfo,Sitecore.Commerce.Connect.DynamicsRetail.Models.CommerceLoyaltyCardPaymentInfo)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "member", Target = "Sitecore.Reference.Storefront.Controllers.CheckoutController.#AddSupportingDataToViewBag(Sitecore.Commerce.Connect.CommerceServer.Orders.Models.CommerceCart,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.AddToCartViewModel.#ProductUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.AddToCartViewModel.#ImageUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Infos", Scope = "member", Target = "Sitecore.Reference.Storefront.InputModelExtension.#ToShippingInfos(System.Collections.Generic.List`1<Sitecore.Reference.Storefront.Models.InputModels.Cart.ShippingMethodInputModelItem>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "IDs", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.InputModels.Cart.ShippingMethodInputModelItem.#LineIDs")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.InputModels.Cart.ShippingMethodInputModelItem.#LineIDs")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "CardIn", Scope = "member", Target = "Sitecore.Reference.Storefront.Services.ILoyaltyCardService.#UpdateLoyaltyCardInCart(System.String,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.JsonResults.OrderHeaderItemJsonResult.#DetailsUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.JsonResults.WishListHeaderItemJsonResult.#DetailsUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.JsonResults.WishListJsonResult.#Lines")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Elegible", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.JsonResults.LoyaltyTierItemJsonResult.#IsElegible")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.JsonResults.AddressItemJsonResult.#DetailsUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.ProductViewModel.#ProductUrl")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "by")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "member", Target = "Sitecore.Reference.Storefront.Controllers.LoyaltyController.#GetLoyaltyCards()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "Sitecore.Reference.Storefront.Models.JsonResults.SubmitOrderJsonResult.#Initialize(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Girst", Scope = "member", Target = "Sitecore.Reference.Storefront.CommerceServerStorefrontConstants+KnownFieldNames.#SupportsGirstCardPayment")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "Sitecore.Reference.Storefront.Connect.Pipelines.Prices.GetProductBulkPricesFromIndex.#Process(Sitecore.Commerce.Pipelines.ServicePipelineArgs)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId = "2#", Scope = "member", Target = "Sitecore.Reference.Storefront.Controllers.CatalogController.#SetSortParameters(Sitecore.Reference.Storefront.Models.SitecoreItemModels.Category,System.String&,System.Nullable`1<Sitecore.Commerce.Connect.CommerceServer.CommerceConstants+SortDirection>&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1045:DoNotPassTypesByReference", MessageId = "1#", Scope = "member", Target = "Sitecore.Reference.Storefront.Controllers.CatalogController.#SetSortParameters(Sitecore.Reference.Storefront.Models.SitecoreItemModels.Category,System.String&,System.Nullable`1<Sitecore.Commerce.Connect.CommerceServer.CommerceConstants+SortDirection>&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "member", Target = "Sitecore.Reference.Storefront.Controllers.AccountController.#RecentOrders()")]